### ISSUE TITLE
求传个百度云

### ISSUE THREAD

**Issue by sssadfs** [JunASAKA/Tablet-Reflashing#1]
这堆东西太大了，一直是下载几个M就停了，完全没法下载完整
我尝试用Gitee导入第三方的仓库来下载可却因为太大了而失败了
因此强烈求传百度云

**Comment by JunASAKA** [comment]
同志你好：
　　文件已上传至百度网盘，链接地址：https://pan.baidu.com/s/1ZiHeBFROUN1-jaxTqsAccw 
；密码：z0qp。但私以为在正常情况下GitHub应该比百度网盘快:-* 。

　　顺祝，
秋安。

浅香ジュン





在2020年09月13 13时39分，"sssadfs"<notifications@github.com>写道：


这堆东西太大了，一直是下载几个M就停了，完全没法下载完整
我尝试用Gitee导入第三方的仓库来下载可却因为太大了而失败了
因此强烈求传百度云

**Comment by sssadfs** [comment]
多谢。
